### ISSUE TITLE
Required DLLs

### ISSUE THREAD

**Issue by ajos6183** [wo80/csparse-interop#1]
Hi @Wo80,

I was having a look at this project to see how much faster it would be compared to CSparse for my particular usage and it seems that it requires 5 external DLLs (libumfpack.dll, libcholmod.dll, libspqr.dll, libsuperlu.dll, mkl_rt.dll). However, i don't have enough knowledge and experience to be able to generate these from their respective source codes. Would it be possible to upload those DLLs?

Thanks,
Anthony

**Comment by wo80** [comment]
I cannot redistribute the MKL dlls. You'll have to install the [Intel MKL community edition](https://software.intel.com/en-us/articles/free-ipsxe-tools-and-libraries).

Here's a temporary link for the other dlls: [dist.7z](http://wo80.bplaced.net/dl.php?p=0-B71AA64C)

If you are running the benchmark included with this project, I'd be glad to see your results.

**Comment by ajos6183** [comment]
Thank you so much @wo80. Here are the results on my laptop for the benchmark.

[X64-benchmark-pardiso.txt](https://github.com/wo80/csparse-interop/files/1915698/X64-benchmark-pardiso.txt)
[X64-benchmark-superlu.txt](https://github.com/wo80/csparse-interop/files/1915699/X64-benchmark-superlu.txt)
[X64-benchmark-umfpack.txt](https://github.com/wo80/csparse-interop/files/1915700/X64-benchmark-umfpack.txt)
[X64-benchmark-cholmod.txt](https://github.com/wo80/csparse-interop/files/1915701/X64-benchmark-cholmod.txt)
[X86-benchmark-pardiso.txt](https://github.com/wo80/csparse-interop/files/1915706/X86-benchmark-pardiso.txt)
[X86-benchmark-superlu.txt](https://github.com/wo80/csparse-interop/files/1915707/X86-benchmark-superlu.txt)
[X86-benchmark-umfpack.txt](https://github.com/wo80/csparse-interop/files/1915708/X86-benchmark-umfpack.txt)
[X86-benchmark-cholmod.txt](https://github.com/wo80/csparse-interop/files/1915709/X86-benchmark-cholmod.txt)

**Comment by wo80** [comment]
Thanks for posting the results.
