### ISSUE TITLE
SuiteSparse on Linux

### ISSUE THREAD

**Issue by vstembera** [wo80/csparse-interop#13]
Hi @wo80,

it is me again. UMFPACK and other SuiteSparse libraries work fine now, the current problem is that I need to switch to a Linux computer at the Uni which has 2TB RAM (due to large problems which I need to solve). What would currently help me a lot are the SuiteSparse dll(=so) libraries for Linux. I have already found MKLPardiso .so version and it, together with my C# project incl.Interop, works well. The only thing now, which I miss, is the so version of SuitSparse. Could you eventually help me with this?

Thanks,

Vita

**Comment by wo80** [comment]
Which distro are you using?

I currently only have Manjaro  installed. It's an Arch based distro which uses `pacman` as a package manager. It provides a `suitesparse` package which works well with the CSparse.NET interop code.

If you're on a Debian based distro, try to use `apt-cache search suitesparse` and if the packages are available do `apt install package-name`. For UMFPACK on Ubuntu, the package name is `libumfpack5`, see [here](https://packages.ubuntu.com/search?keywords=libumfpack&searchon=names&suite=jammy&section=all).

For RHEL based distros use `dnf` to manage packages.

If no packages are provided by your distro, you'll have to compile SuiteSparse for yourself. Just run `make` and `make install` and you should be ready to go.

**Comment by wo80** [comment]
Then a `sudo apt install libumfpack5` should be enough. If you don't have root privileges, ask your admin to install the package.

To check whether the library has 64-bit integer support, do `nm -D /usr/lib/libumfpack.so.5` and look for the `umfpack_dl_*` functions.

**Comment by vstembera** [comment]
Thanks, I try it.

**Comment by wo80** [comment]
Did this work out?
I'll close the issue, but feel free to re-open.

**Comment by vstembera** [comment]
Yes, it works now. Sorry, I should have written some comment here earlier.
