### ISSUE TITLE
Any plan to support MKL sparse QR?

### ISSUE THREAD

**Issue by hxhc** [wo80/csparse-interop#18]
Dear @wo80 ,

Thanks for the great work to help using sparse sovlers in C#. I am a newbie to sparse sovlers and I made a incomprehensive survey of direct solvers. Obviously suitesparse and pardiso are the most common solvers, which you have already integrated into the project. 

While it is quite fast especially for large matrices, according to your benchmark result, pardiso can only cope with square matrices. MKL has introduced [sparse qr solver](https://www.intel.com/content/www/us/en/developer/articles/technical/intel-mkl-sparse-qr-solver-multifrontal-sparse-qr-factorization-method-for-solving-a-sparse.html) which shows much higher performance over SuiteSparse SPQR. I am wondering if you have any plan to implement the interface between CSparse.net and mkl Sparse QR. Since I am a newbie to both sparse sovlers and C#, I just can't make a PR in short time. If you are busy, maybe I can try a simple version some time later. Anyway, the project is terrific, thank you again!

**Comment by hxhc** [comment]
Glad to hear that, closing the issue for you have already written the code.😁

**Comment by wo80** [comment]
The code is online now. Please test and report any issues.

**Comment by hxhc** [comment]
> The code is online now. Please test and report any issues.
Sure, I'll test the function soon.
