### ISSUE TITLE
how to apply triplets

### ISSUE THREAD

**Issue by falkantara** [wo80/csparse-interop#7]
Hi 
I tried your test benchmarks, but I was wondering how to apply real worlds (FEM) application triplets directly (a.k.a COO matrix) to these tests.

See below my computer benchmark test results. 
My Specs: Intel Core i7-4790 processor (8M Cache, up to 4.00 GHz) 16GB DDR3
NVIDIA GeForce GTX 745M 4GB

Running tests (Double) ... [N = 2500]

Testing UMFPACK ... [1.587s] OK
Testing UMFPACK (symmetric) ... [1.297s] OK
Testing CHOLMOD (symmetric) ... [0.556s] OK
Testing SPQR ... [6.645s] OK
Testing SPQR (symmetric) ... [6.569s] OK
Testing SuperLU ... [1.842s] OK
Testing SuperLU (symmetric) ... [0.875s] OK
Testing PARDISO ... [0.649s] OK
Testing PARDISO (symmetric) ... [0.401s] OK

Running eigensolver tests (Double) ... [N = 2500]

Testing ARPACK ... [0.016s] OK
Testing FEAST ... [0.148s] OK
Testing MKL Extended Eigensolver ... [0.057s] OK

Best

**Comment by wo80** [comment]
Use `CSparse.Storage.CoordinateStorage<T>` to build the storage and the convert to CSC:
```c#
using CSparse.Double;
using CSparse.Storage;

var coo = new CoordinateStorage<double>(rows, columns, nnz);

// Do FEM stuff and fill storage using coo.At(i, j, value).
BuildStorage(coo);

var A = (SparseMatrix)CSparse.Converter.ToCompressedColumnStorage(coo);
```

**Comment by falkantara** [comment]
Okay I tried
even though my matrix is definitely symmetric positive definite since its coming from FEM matrix, it gives an error just like in CSparse

**Comment by wo80** [comment]
Which native solver are you trying to use, what error do you get?
> it gives an error just like in CSparse

Which factorization did you try? Cholesky? Have tried LU or QR?

**Comment by falkantara** [comment]
Hello
I tried only Cholesky, I passed the only upper part since its symmetric positive definite am I wrong

**Comment by wo80** [comment]
Try the following code:
```c#
try
{
    var lower = A.Transpose(); // Make lower (represents upper in CSR format, expected by PARDISO)

    using (var pardiso = new Pardiso(lower, PardisoMatrixType.RealSymmetricPositiveDefinite))
    {
        var opt = pardiso.Options;

        opt.ColumnOrderingMethod = PardisoOrdering.MinimumDegree;
        opt.CheckMatrix = true;
        opt.ZeroBasedIndexing = true;

        pardiso.Solve(b, x);
    }
}
catch (Exception e)
{
    Console.WriteLine(e.Message);
}
```
* Since - for symmetric problems - PARDISO expects the upper part of the matrix in CSR format, you'll have to transpose the CSparse matrix (since it uses CSC format).
* Set option `CheckMatrix = true`. This way, PARDISO will check the storage and won't try to factorize, if there's a problem.
* In `CSparse.Interop.Pardiso.PardisoContext` set `msglvl = 1` to get debug info from PARDISO printed to console.
