### ISSUE TITLE
some dlls are required

### ISSUE THREAD

**Issue by skspanda520** [wo80/csparse-interop#8]
Hello @wo80,

I am trying to convert matlab built in function colamd(S) to C#, and thankfully I found csparse-interop is a perfectly matched solution. But the problem is it nees some dlls like libamd.dll etc. Can I ask how I can find these dlls?

**Comment by wo80** [comment]
You can download dlls [here](http://wo80.bplaced.net/math/packages.html) or build them yourself: https://github.com/wo80/vs-suitesparse/

**Comment by skspanda520** [comment]
Thank U so much!! It works well!! :-)
