### ISSUE TITLE
Pardiso solver problem

### ISSUE THREAD

**Issue by AlbertLiDesign** [wo80/csparse-interop#9]
![image](https://user-images.githubusercontent.com/39052060/103132522-e47d4b80-46df-11eb-82e2-e5c3105e34c8.png)

Hi, I'm trying the pardiso solver. I've moved 'mkl_intel_thread.dll', 'mkl_rt.dll' to the folder the directory where my .exe files are located. But I got an error here. It means 'External component has thrown an exception'. My matrix can be successfully solved by other solvers. I don't know where the problem is. Could you please help me? 

The matrix can be downloaded here
[matrix.zip](https://github.com/wo80/csparse-interop/files/5741782/matrix.zip)

**Comment by wo80** [comment]
Somehow, `PardisoMatrixType.RealSymmetricPositiveDefinite` doesn't seem to work, use `RealStructurallySymmetric` instead. If you get it working with `RealSymmetricPositiveDefinite`, please let me know!

Additionally, I found a problem in the `PardisoContext` [constructor](https://github.com/wo80/csparse-interop/blob/master/CSparse.Interop/Interop/MKL/Pardiso/PardisoContext.cs#L54):
```c#
line 65: options.SetDefault();
line 67: DoInitialize();
```
`DoInitialize()` will reset all default values, so make sure setup the solver options manually like done in the [TestPardiso](https://github.com/wo80/csparse-interop/blob/master/CSparse.Benchmark/Double/Tests/TestPardiso.cs#L15) example code.

Also make sure that all [dependencies](https://github.com/wo80/csparse-interop/wiki/Dependencies) are available.

**Comment by wo80** [comment]
> I've moved 'mkl_intel_thread.dll', 'mkl_rt.dll' to the folder where my .exe files are located.
I usually have all my native libraries in a common path like `C:\lib\x64` and then add this to the `PATH` environment variable.

**Comment by wo80** [comment]
Using `RealSymmetricIndefinite` also works. I guess the provided matrix isn't positive definite.

**Comment by AlbertLiDesign** [comment]
Hi, thank you for your patient reply.

Okay! It works. The reason is that I lack dependency libraries. 

Thank you soooo much!
